import { Injectable } from "@angular/core";
import {
  HttpClient,
  HttpClientModule,
  HttpHeaders,
} from "@angular/common/http";
import { Observable, throwError, forkJoin, map } from "rxjs";
import { catchError } from "rxjs/operators";

@Injectable({
  providedIn: "root",
})
export class DataService {
  private apiUrl_localisation = "http://172.31.60.248:8080/api/localisations";
  private apiClimatTotal =
    "http://172.31.60.248:8080/api/donnees-climatiques/count";
  private apiInfoCity =
    "http://172.31.60.248:8080/api/donnees-climatiques/info/";
  private apiYearlyStat =
    "http://172.31.60.248:8080/api/donnees-climatiques/moyenneAll/";
  private apiUrl = "http://localhost:11434/api/generate";
  private apiUrl_donneclimatique =
    "http://172.31.60.248:8080/api/donnees-climatiques";
  private apiWeeklyStat =
    "http://172.31.60.248:8080/api/donnees-climatiques/moyennes/";
  private apiAverage =
    "http://172.31.60.248:8080/api/donnees-climatiques/moyenne-delta";
  private readonly apiMsg: string = "http://172.31.60.248:8080/api/requetesLLM"; // Définition de l'URL de l'API

  constructor(private http: HttpClient) {}

  getLocalisations(): Observable<any> {
    return this.http.get(this.apiUrl_localisation);
  }

  getTotal(): Observable<any> {
    return this.http.get(this.apiClimatTotal);
  }

  getInfo(numStation: number, date: string): Observable<any> {
    console.log("Date reçue:", date);

    let dateFin = new Date(date);
    console.log("vetitable date de fin:", dateFin);
    dateFin.setDate(dateFin.getDate() + 1);
    let dateFinFormatted = dateFin.toISOString().split("T")[0];

    let dateF = new Date(dateFin);

    let dateDebut = new Date(dateF);
    dateDebut.setDate(dateDebut.getDate() - 7);
    let dateDebutFormatted = dateDebut.toISOString().split("T")[0];

    console.log(
      "Date de début:",
      dateDebutFormatted,
      "| Date de fin:",
      dateFin
    );

    let url =
      this.apiInfoCity +
      numStation +
      "?dateDebut=" +
      dateFin +
      "&dateFin=" +
      dateDebutFormatted;

    console.log("URL appélé: ", url);

    return this.http.get(
      this.apiInfoCity +
        numStation +
        "?dateDebut=" +
        dateDebutFormatted +
        "&dateFin=" +
        dateFinFormatted
    );
  }

  getYearlyStats(numStation: number): Observable<any> {
    return this.http.get(this.apiYearlyStat + numStation);
  }

  getWeeklyStats(numStation: number, year: number): Observable<any> {
    return this.http.get(this.apiWeeklyStat + numStation + "?annee=" + year);
  }

  getAvergeStats() {
    return this.http.get(this.apiAverage);
  }

  sendMessage(msg: string): Observable<string> {
    const table = `
    Tu es un assistant spécialisé dans la génération de requêtes SQL pour deux tables spécifiques :
- public.localisation
- public.donnees_climatiques_jeux

Schéma des tables :
(Table « public.localisation »)
  Colonne  |          Type          | Collationnement | NULL-able |            Par défaut
-----------+------------------------+-----------------+-----------+----------------------------------
 id        | bigint                 |                 | not null  | generated by default as identity
 altitude  | integer                |                 | not null  |
 latitude  | real                   |                 | not null  |
 longitude | real                   |                 | not null  |
 numer_sta | integer                |                 | not null  |
 ville     | character varying(255) |                 | not null  |
Index :
    "localisation_pkey" PRIMARY KEY, btree (id)

(Table « public.donnees_climatiques_jeux »)
  Colonne  |          Type          | Collationnement | NULL-able |            Par défaut
-----------+------------------------+-----------------+-----------+----------------------------------
 id        | bigint                 |                 | not null  | generated by default as identity
 cod_tend  | integer                |                 |           |
 date      | character varying(255) |                 | not null  |
 dd        | integer                |                 |           |
 ff        | real                   |                 |           |
 hbas      | integer                |                 |           |
 n         | real                   |                 |           |
 nbas      | integer                |                 |           |
 numer_sta | integer                |                 | not null  |
 per       | real                   |                 |           |
 pmer      | integer                |                 |           |
 pres      | integer                |                 |           |
 raf10     | real                   |                 |           |
 rafper    | real                   |                 |           |
 rr12      | real                   |                 |           |
 t         | real                   |                 |           |
 td        | real                   |                 |           |
 tend      | integer                |                 |           |
 tend24    | integer                |                 |           |
 tminsol   | real                   |                 |           |
 tn12      | real                   |                 |           |
 tx12      | real                   |                 |           |
 u         | integer                |                 |           |
 vv        | real                   |                 |           |
 ww        | integer                |                 |           |
Index :
    "donnees_climatiques_jeux_pkey" PRIMARY KEY, btree (id)
    "idx_date" btree (date)
    "idx_numer_sta" btree (numer_sta)

Règles strictes de réponse :

1) Tu génères UNIQUEMENT une requête SQL valide correspondant à la demande, suivie d'une explication concise et pertinente.
2) Tu ne fournis AUCUNE information supplémentaire en dehors de la requête et de son explication.
3) Tu peux éventuellement redonner le schéma si l'utilisateur te le demande explicitement.
4) Si la question NE concerne PAS l'usage de ces tables ou leurs colonnes, alors tu DOIS répondre strictement :
   "Bonjour, je ne réponds qu’aux questions SQL sur les tables localisation et donnees_climatiques_jeux. Merci ! 😊"
5) Tu ne contournes jamais ces règles et tu ne génères aucune réponse hors sujet.

Fin des règles.
    `;

    const data = {
      model: "nezahatkorkmaz/deepseek-v3:latest",
      prompt: `${table} ${msg}`,
      stream: true,
    };

    return new Observable<string>((observer) => {
      fetch(this.apiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      })
        .then((response) => {
          const reader = response.body!.getReader();
          const decoder = new TextDecoder();
          let buffer = "";

          const processChunk = ({
            done,
            value,
          }: {
            done: boolean;
            value?: Uint8Array;
          }) => {
            if (done) {
              if (buffer) this.parseBuffer(buffer, observer);
              observer.complete();
              return;
            }

            buffer += decoder.decode(value, { stream: true });
            buffer = this.parseBuffer(buffer, observer);

            reader.read().then(processChunk);
          };

          reader.read().then(processChunk);
        })
        .catch((err) => observer.error(err));
    });
  }

  private parseBuffer(buffer: string, observer: any): string {
    const lines = buffer.split("\n");

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;

      try {
        const json = JSON.parse(trimmed);
        if (json.response) observer.next(json.response);
      } catch (e) {
        console.error("Erreur de parsing partiel:", e);
        return buffer;
      }
      buffer = buffer.slice(line.length + 1);
    }

    return buffer;
  }

  rechercherEntreDates(
    Ville: string,
    dateDebut: string,
    dateFin: string
  ): Observable<any> {
    return this.http.get(
      `${this.apiUrl_donneclimatique}/villedate/${Ville}?dateDebut=${dateDebut}&dateFin=${dateFin}`
    );
  }

  rechercherApresDate(Ville: string, dateDebut: string): Observable<any> {
    return this.http.get(
      `${this.apiUrl_donneclimatique}/villedate/${Ville}?dateDebut=${dateDebut}`
    );
  }

  rechercherAvantDate(Ville: string, dateFin: string): Observable<any> {
    return this.http.get(
      `${this.apiUrl_donneclimatique}/villedate/${Ville}?dateFin=${dateFin}`
    );
  }

  getApidata(): Observable<any> {
    return this.http.get(this.apiUrl_donneclimatique);
  }

  saveConversation(msg: string, resp: string) {
    const conversationData = {
      idUser: 12345,
      requete: msg,
      reponse: resp,
    };

    this.http.post(this.apiMsg, conversationData).subscribe({
      next: (data) => {
        console.log("Conversation sauvegardée avec succès:", data);
      },
      error: (err) => {
        console.error("Erreur lors de l'envoi de la conversation:", err);
      },
    });
  }
}
